// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import {
  DASHBOARD_USER_ID_HEADER,
  getAuthorizedUserIdFromSearch,
} from '@/lib/accessControl';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing Supabase environment variables. Configure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY."
  );
}

const dashboardAwareFetch: typeof fetch = (input, init) => {
  const headers = new Headers(init?.headers);

  if (typeof window !== "undefined") {
    const authorizedUserId = getAuthorizedUserIdFromSearch(window.location.search);

    if (authorizedUserId) {
      headers.set(DASHBOARD_USER_ID_HEADER, authorizedUserId);
    } else {
      headers.delete(DASHBOARD_USER_ID_HEADER);
    }
  }

  return fetch(input, {
    ...init,
    headers,
  });
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: dashboardAwareFetch,
  },
});
