// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoqcazkwclpngawmwbon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvcWNhemt3Y2xwbmdhd213Ym9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyOTU0OTIsImV4cCI6MjA4OTg3MTQ5Mn0.ngB5laERhxrONnj2U71T8_R8ugS4uzMuOAuFx1twfcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});